### ISSUE TITLE
The "stateSave" option doesn't work

### ISSUE THREAD

**Issue by cataragak90** [DataTables/Scroller#80]
I use the "stateSave = true" option but the scrolling position is not restored after page reload. I also could reproduce the issue on the official demo page (https://datatables.net/extensions/scroller/examples/initialisation/state_saving.html).
Is there a way to make it work?

PS: it worked on the previous version

**Comment by DataTables** [comment]
Can you try the nightly version please? https://datatables.net/download/nightly .

**Comment by cataragak90** [comment]
> Can you try the nightly version please? https://datatables.net/download/nightly .

I have the same problem

**Comment by DataTables** [comment]
Okay - thanks for letting me know about this. I'll post back once I've had a chance to look into it.

**Comment by smartymann** [comment]
H there,
just started a new project using datatables and scroller and can confirm, that the stateSave and scrollPosition is not working anymore. Went one version back and everything is working again.

**Comment by terracatta** [comment]
I believe I am facing this issue as well with Scroller 2.0.0. I am using Scroller with server side processing enabled. When I scroll down a large data-set and then go back to the table, the scroll position appears to be maintained but I cannot scroll the dataset up (it appears I am at the top of the dataset when I am not).

If I downgrade to release 1.5.x, this feature works as expected.

**Comment by oprudkyi** [comment]
Hi, as for Scroller version 2.0.2 even sample from https://datatables.net/extensions/scroller/examples/initialisation/state_saving.html doesn't work at all, I see 

```
jQuery.Deferred exception: Cannot read property 'scroller' of null TypeError: Cannot read property 'scroller' of null
    at HTMLTableElement.<anonymous> (https://cdn.datatables.net/scroller/2.0.2/js/dataTables.scroller.min.js:26:93)
    at HTMLTableElement.dispatch (https://code.jquery.com/jquery-3.5.1.js:5429:27)
    at HTMLTableElement.elemData.handle (https://code.jquery.com/jquery-3.5.1.js:5233:28)
    at Object.trigger (https://code.jquery.com/jquery-3.5.1.js:8715:12)
    at HTMLTableElement.<anonymous> (https://code.jquery.com/jquery-3.5.1.js:8793:17)
    at Function.each (https://code.jquery.com/jquery-3.5.1.js:381:19)
    at jQuery.fn.init.each (https://code.jquery.com/jquery-3.5.1.js:203:17)
    at jQuery.fn.init.trigger (https://code.jquery.com/jquery-3.5.1.js:8792:15)
    at A (https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js:90:157)
    at jQuery.fn.init.Aa (https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js:86:1) undefined

Uncaught TypeError: Cannot read property 'scroller' of null
    at HTMLTableElement.<anonymous> (dataTables.scroller.min.js:26)
    at HTMLTableElement.dispatch (jquery-3.5.1.js:5429)
    at HTMLTableElement.elemData.handle (jquery-3.5.1.js:5233)
    at Object.trigger (jquery-3.5.1.js:8715)
    at HTMLTableElement.<anonymous> (jquery-3.5.1.js:8793)
    at Function.each (jquery-3.5.1.js:381)
    at jQuery.fn.init.each (jquery-3.5.1.js:203)
    at jQuery.fn.init.trigger (jquery-3.5.1.js:8792)
    at A (jquery.dataTables.min.js:90)
    at jQuery.fn.init.Aa (jquery.dataTables.min.js:86)
```

**Comment by DataTables** [comment]
Yes, sorry about that. It was [fixed here](https://github.com/DataTables/Scroller/commit/88a8d751688fd84607e14bdad16ac53c9f770598). We’ll do a patch release soon.
